SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
WHERE II.ITEM_ID NOT IN(
    SELECT IT2.PARENT_ITEM_ID
    FROM ITEM_TREE IT2
    WHERE PARENT_ITEM_ID IS NOT NULL
    )
ORDER BY II.ITEM_ID DESC