SELECT *
FROM (
    SELECT DATE_FORMAT(OS.SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
           OS.PRODUCT_ID,
           OS.USER_ID,
           OS.SALES_AMOUNT
    FROM ONLINE_SALE AS OS
    WHERE DATE_FORMAT(OS.SALES_DATE, "%Y-%m") = '2022-03'

    UNION ALL

    SELECT DATE_FORMAT(FS.SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
           FS.PRODUCT_ID,
           NULL AS USER_ID,
           FS.SALES_AMOUNT
    FROM OFFLINE_SALE AS FS
    WHERE DATE_FORMAT(FS.SALES_DATE, "%Y-%m") = '2022-03'
) AS TT
ORDER BY TT.SALES_DATE ASC, TT.PRODUCT_ID ASC, TT.USER_ID ASC;
