SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
JOIN (
    SELECT RI2.REST_ID, MAX(RI2.FAVORITES) AS MAX_FAV
    FROM REST_INFO RI2
    GROUP BY RI2.FOOD_TYPE
) TMP
ON RI.FAVORITES = TMP.MAX_FAV       
GROUP BY RI.FOOD_TYPE
ORDER BY RI.FOOD_TYPE DESC