SELECT CC1.CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR CC1
WHERE 
    OPTIONS LIKE '%통풍시트%'
    OR OPTIONS LIKE '%열선시트%'
    OR OPTIONS LIKE '%가죽시트%'
GROUP BY CC1.CAR_TYPE
ORDER BY CC1.CAR_TYPE