WITH RECURSIVE ECOLI_TREE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA AS ED
    WHERE ED.PARENT_ID IS NULL

    UNION ALL

    SELECT ED.ID, ET.GENERATION + 1
    FROM ECOLI_DATA ED
        JOIN ECOLI_TREE ET
        ON ED.PARENT_ID = ET.ID
),
NO_CHILDREN AS (
    SELECT ET.ID, ET.GENERATION
    FROM ECOLI_TREE ET
        LEFT JOIN ECOLI_DATA ED
        ON ET.ID = ED.PARENT_ID
    WHERE ED.ID IS NULL
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM NO_CHILDREN
GROUP BY GENERATION
ORDER BY GENERATION;
