SELECT
    ED.ID AS ID,
    CASE
        WHEN ED.SIZE_OF_COLONY <= 100 THEN 'LOW'
        WHEN ED.SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SIZE
FROM ECOLI_DATA AS ED
ORDER BY ED.ID ASC