SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO AS II
WHERE II.ITEM_ID IN 
    (
        SELECT IT.ITEM_ID
        FROM
            ITEM_INFO AS II
            JOIN
            ITEM_TREE AS IT
            ON II.ITEM_ID = IT.PARENT_ITEM_ID
        WHERE II.RARITY = 'RARE'
    )
ORDER BY II.ITEM_ID DESC