SELECT ED.ID, ED.GENOTYPE, EDP.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA AS ED
    JOIN
    ECOLI_DATA AS EDP
    ON ED.PARENT_ID = EDP.ID
WHERE (ED.GENOTYPE & EDP.GENOTYPE)  = EDP.GENOTYPE
ORDER BY ED.ID