SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM
    SKILLCODES AS SC
    JOIN
    DEVELOPERS AS D
    ON
        SC.CODE & D.SKILL_CODE > 0
WHERE SC.NAME = 'Python' OR SC.NAME = 'C#'
ORDER BY D.ID