SELECT 
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    (MAX_ED.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV,
    ED.ID
FROM 
    ECOLI_DATA ED
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY 
        YEAR(DIFFERENTIATION_DATE)
) MAX_ED
ON YEAR(ED.DIFFERENTIATION_DATE) = MAX_ED.YEAR
ORDER BY 
    YEAR ASC, 
    YEAR_DEV ASC;
