SELECT FI.ID AS ID, FN.FISH_NAME AS FISH_NAME, FI.LENGTH AS LENGTH
FROM FISH_INFO FI
NATURAL JOIN FISH_NAME_INFO FN
WHERE (FI.FISH_TYPE, FI.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY ID;
