name: Move Date Folders into Codetree and Retain Commit Message

on:
  push:
    paths:
      - '[0-9][0-9][0-1][0-9][0-3][0-9]/**/*'

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get last commit message
        id: lastcommit
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "message=$msg" >> $GITHUB_OUTPUT

      - name: Move all yyMMdd folders to Codetree/
        run: |
          mkdir -p Codetree
          for dir in [0-9][0-9][0-1][0-9][0-3][0-9]; do
            if [ -d "$dir" ]; then
              echo "Moving $dir to Codetree/$dir"
              rm -rf Codetree/"$dir"
              mv "$dir" Codetree/
              if [ -d "$dir" ]; then
                echo "Force removing leftover $dir"
                rm -rf "$dir"
              fi
            fi
          done

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "oxdjww"
          git config user.email "oxdjww@gmail.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "${{ steps.lastcommit.outputs.message }}"
            git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
          fi
